package com.amm.poc.springredis.application;

/*
SERVICE LAYER - USE CASE LAYER
CREATE A SERVICE CLASS FOR EVERY USE CASE
CALL IT USE CASE, NOT SERVICE
DON'T USE SPRING ANNOTATIONS
ONLY USE IMPLEMENTATIONS
 */