package com.amm.poc.springredis.infrastructure;

/*
INFRASTRUCTURE LAYER - USE SPRING OBJECTS, JPA OBJECTS, ETC
CREATE SPRING CONTROLLERS, SPRING REPOSITORY IMPLEMENTATIONS AND SO ON.
IMPLEMENT INTERFACES WHICH ARE CREATED IN THE DOMAIN LAYER
 */