package com.amm.poc.springredis.domain;

/*
DOMAIN LAYER - USE POJOS
CREATE POJOS, PUT USE CASE THE LOGIC INSIDE
DOMAIN OBJECTS
DON'T USE SPRING ANNOTATIONS
ONLY USE IMPLEMENTATIONS FOR THE DOMAIN OBJECTS
DEFINE AND USE INTERFACES WHICH ARE IMPLEMENTED IN THE INFRASTRUCTURE LAYER
 */